version: '2.2'
services:
  exchange-rate-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: exchange-rate-service
    ports:
      - 8080
    networks:
      - network1
networks:
  network1: